# Generated by Django 4.1.7 on 2023-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_description_alter_project_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=700),
        ),
    ]
