# Generated by Django 4.1.7 on 2023-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='resource',
            new_name='youtubeResource',
        ),
        migrations.AddField(
            model_name='project',
            name='imageResource',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
