# Generated by Django 4.1.7 on 2023-02-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_resource_project_youtuberesource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imageResource',
            new_name='imageResourceID',
        ),
    ]
